package com.vaadin.addon.sqlcontainer.query.generator;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Time;
import java.sql.Timestamp;
import java.sql.Types;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * StatementHelper is a simple helper class that assists TableQuery and the
 * query generators in filling a PreparedStatement. The actual statement is
 * generated by the query generator methods, but the resulting statement and all
 * the parameter values are stored in an instance of StatementHelper.
 * 
 * This class will also fill the values with correct setters into the
 * PreparedStatement on request.
 */
public class StatementHelper {

    private String queryString;

    private List<Object> parameters = new ArrayList<Object>();
    private Map<Integer, Class<?>> dataTypes = new HashMap<Integer, Class<?>>();

    public StatementHelper() {
    }

    public void setQueryString(String queryString) {
        this.queryString = queryString;
    }

    public String getQueryString() {
        return queryString;
    }

    public void addParameterValue(Object parameter) {
        if (parameter != null) {
            parameters.add(parameter);
            dataTypes.put(parameters.size() - 1, parameter.getClass());
        }
    }

    public void addParameterValue(Object parameter, Class<?> type) {
        parameters.add(parameter);
        dataTypes.put(parameters.size() - 1, type);
    }

    public void setParameterValuesToStatement(PreparedStatement pstmt)
            throws SQLException {
        for (int i = 0; i < parameters.size(); i++) {
            if (dataTypes.get(i) == null) {
                handleNullValue(i, pstmt);
            } else {
                pstmt.setObject(i + 1, parameters.get(i));
            }

            // } else if (parameters.get(i) instanceof BigDecimal) {
            // pstmt.setBigDecimal(i + 1, (BigDecimal) parameters.get(i));
            // } else if (parameters.get(i) instanceof Boolean) {
            // pstmt.setBoolean(i + 1, (Boolean) parameters.get(i));
            // } else if (parameters.get(i) instanceof Byte) {
            // pstmt.setByte(i + 1, (Byte) parameters.get(i));
            // } else if (parameters.get(i) instanceof Date) {
            // pstmt.setDate(i + 1, (Date) parameters.get(i));
            // } else if (parameters.get(i) instanceof Double) {
            // pstmt.setDouble(i + 1, (Double) parameters.get(i));
            // } else if (parameters.get(i) instanceof Float) {
            // pstmt.setFloat(i + 1, (Float) parameters.get(i));
            // } else if (parameters.get(i) instanceof Integer) {
            // pstmt.setInt(i + 1, (Integer) parameters.get(i));
            // } else if (parameters.get(i) instanceof Long) {
            // pstmt.setLong(i + 1, (Long) parameters.get(i));
            // } else if (parameters.get(i) instanceof Short) {
            // pstmt.setShort(i + 1, (Short) parameters.get(i));
            // } else if (parameters.get(i) instanceof String) {
            // pstmt.setString(i + 1, (String) parameters.get(i));
            // } else if (parameters.get(i) instanceof Time) {
            // pstmt.setTime(i + 1, (Time) parameters.get(i));
            // } else if (parameters.get(i) instanceof Timestamp) {
            // pstmt.setTimestamp(i + 1, (Timestamp) parameters.get(i));
            // } else {
            // throw new SQLException(
            // "Data type not supported by SQLContainer: "
            // + parameters.get(i).getClass().toString());
        }

        /*
         * The following setX methods of PreparedStatement are NOT used here ->
         * these data types are not supported.
         * 
         * setNCharacterStream(int parameterIndex, Reader value)
         * 
         * setNClob(int parameterIndex, NClob value)
         * 
         * setNString(int parameterIndex, String value)
         * 
         * setObject(int parameterIndex, Object x)
         * 
         * setRef(int parameterIndex, Ref x)
         * 
         * setRowId(int parameterIndex, RowId x)
         * 
         * setSQLXML(int parameterIndex, SQLXML xmlObject)
         * 
         * setBytes(int parameterIndex, byte[] x)
         * 
         * setCharacterStream(int parameterIndex, Reader reader)
         * 
         * setClob(int parameterIndex, Clob x)
         * 
         * setURL(int parameterIndex, URL x)
         * 
         * setArray(int parameterIndex, Array x)
         * 
         * setAsciiStream(int parameterIndex, InputStream x)
         * 
         * setBinaryStream(int parameterIndex, InputStream x)
         * 
         * setBlob(int parameterIndex, Blob x)
         */
    }

    private void handleNullValue(int i, PreparedStatement pstmt)
            throws SQLException {
        if (BigDecimal.class.equals(dataTypes.get(i))) {
            pstmt.setBigDecimal(i + 1, null);
        } else if (Boolean.class.equals(dataTypes.get(i))) {
            pstmt.setNull(i + 1, Types.BOOLEAN);
        } else if (Byte.class.equals(dataTypes.get(i))) {
            pstmt.setNull(i + 1, Types.SMALLINT);
        } else if (Date.class.equals(dataTypes.get(i))) {
            pstmt.setDate(i + 1, null);
        } else if (Double.class.equals(dataTypes.get(i))) {
            pstmt.setNull(i + 1, Types.DOUBLE);
        } else if (Float.class.equals(dataTypes.get(i))) {
            pstmt.setNull(i + 1, Types.FLOAT);
        } else if (Integer.class.equals(dataTypes.get(i))) {
            pstmt.setNull(i + 1, Types.INTEGER);
        } else if (Long.class.equals(dataTypes.get(i))) {
            pstmt.setNull(i + 1, Types.BIGINT);
        } else if (Short.class.equals(dataTypes.get(i))) {
            pstmt.setNull(i + 1, Types.SMALLINT);
        } else if (String.class.equals(dataTypes.get(i))) {
            pstmt.setString(i + 1, null);
        } else if (Time.class.equals(dataTypes.get(i))) {
            pstmt.setTime(i + 1, null);
        } else if (Timestamp.class.equals(dataTypes.get(i))) {
            pstmt.setTimestamp(i + 1, null);
        } else {
            throw new SQLException("Data type not supported by SQLContainer: "
                    + parameters.get(i).getClass().toString());
        }
    }
}
